### ISSUE TITLE
InflateException in TimePicker

### ISSUE THREAD

**Issue by FranclisJunior** [wdullaer/MaterialDateTimePicker#149]
Hello I'm having the following exception when using the time picker:

I used: timePickerDialog.show(getActivity().getFragmentManager(), TIME_PICKER);

```
android.view.InflateException: Binary XML file line #31: Error inflating class TextView
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                    at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:378)
                                                                                    at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                    at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                                    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:211)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                                 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=26; index=570
                                                                                    at android.content.res.StringBlock.get(StringBlock.java:69)
                                                                                    at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
                                                                                    at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:991)
                                                                                    at android.content.res.TypedArray.getString(TypedArray.java:176)
                                                                                    at android.widget.TextView.<init>(TextView.java:1028)
                                                                                    at android.widget.TextView.<init>(TextView.java:645)
                                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:60)
                                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:56)
                                                                                    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:92)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:938)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:992)
                                                                                    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                    at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:378) 
                                                                                    at android.app.Fragment.performCreateView(Fragment.java:2053) 
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894) 
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                    at android.app.BackStackRecord.run(BackStackRecord.java:834) 
                                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452) 
                                                                                    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                    at android.os.Looper.loop(Looper.java:211) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5389) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by wdullaer** [comment]
I'll need some more information.
Are you trying to set a title on the TimePickerDialog. Is it happening on a tablet?
Is this happening on a real device or in the emulator?

The best would be if you can share me a full code snippet which reliable reproduces the issue (on the emulator and a device).

**Comment by FranclisJunior** [comment]
Hello, it happens in the Xperia Z1 and Emulator Nexus 5.

Are you trying to set a title on the TimePickerDialog? No;
Is it happening on a tablet? No.
Is this happening on a real device or in the emulator? Two.

```
 public static void showTimePickerDialog(FragmentManager fragmentManager, final Button button) {

        TimePickerDialog.OnTimeSetListener listener = new TimePickerDialog.OnTimeSetListener() {
            @Override
            public void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute, int second) {
                button.setText(Masks.hourIntToString(hourOfDay, minute));
            }
        };
        
        Calendar now = Calendar.getInstance();
        TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(
                        listenner,
                        now.get(Calendar.HOUR_OF_DAY),
                        now.get(Calendar.MINUTE),
                        true;
                );
        timePickerDialog.show(fragmentManager, TIME_PICKER);
}
```

Usage :
```
showTimePickerDialog(getActivity().getFragmentManager(), btTime)
```

**Comment by wdullaer** [comment]
would you happen to have an item in your layout with the id `time_picker_header`?

**Comment by FranclisJunior** [comment]
No :/

**Comment by epetrenko** [comment]
Hello, guys.

It seems that I have exactly the same issue both on my Nexus 7 2012 tablet and on Nexus 9 emulator. I use a custom theme in my application, where parameter `<item name="android:fontFamily">sans-serif</item>` is set for whole app (root theme, which extends `Theme.AppCompat.Light.DarkActionBar`). But if I remove that line, problem disappear.

> As @FranclisJunior mentioned, issue is present only for TimePickerDialog. DatePickerDialog works properly without exception.

@wdullaer I hope that my comment will be useful and maybe help you fix this issue.

**Comment by FranclisJunior** [comment]
@epetrenko  Thank you, worked perfectly, just removed the line
 `<item name =" android: fontFamily "> sans-serif </ item>` of my theme.

**Comment by wdullaer** [comment]
This is helpful and should help me triage the issue
