### ISSUE TITLE
InflateException with TimePickerDialog class

### ISSUE THREAD

**Issue by merlip91** [wdullaer/MaterialDateTimePicker#159]
Hello,
First thanks for this library it's amazing! As second, when I try to show TimePickerDialog inside fragment, the component crashes and show me this error:

`Process: habitatprojects.hubbuildings, PID: 22980
                                                                              android.view.InflateException: Binary XML file line #31: Error inflating class TextView
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                  at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:378)
                                                                                  at android.app.Fragment.performCreateView(Fragment.java:1710)
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:891)
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063)
                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450)
                                                                                  at android.app.FragmentManagerImpl$1.run(FragmentManager.java:444)
                                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5105)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: length=26; index=930
                                                                                  at android.content.res.StringBlock.get(StringBlock.java:65)
                                                                                  at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
                                                                                  at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:721)
                                                                                  at android.content.res.TypedArray.getString(TypedArray.java:125)
                                                                                  at android.widget.TextView.<init>(TextView.java:1039)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:48)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
                                                                                  at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:912)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:966)
                                                                                  at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                  at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:378) 
                                                                                  at android.app.Fragment.performCreateView(Fragment.java:1710) 
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:891) 
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063) 
                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450) 
                                                                                  at android.app.FragmentManagerImpl$1.run(FragmentManager.java:444) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:136) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
`

This Exception appear when the TimePickerDialog class try to execute this lane:

`View view = inflater.inflate(R.layout.mdtp_time_picker_dialog, container,false);`

From: 
`public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState){...}`

If you need more information about my code or others, advice me. Thanks in advance and I waiting your answer!!

**Comment by wdullaer** [comment]
Do you by any chance redefine some fonts in your theme?
See #149

**Comment by merlip91** [comment]
I redifine my fonts in some styles (Textview and TextView_Title) but not in main theme. If you need more information advice me. Thanks in advance!

**Comment by wdullaer** [comment]
This is probably the same thing.
Try the version I released yesterday (v2.2.0) and let me know if that fixes your issue.

**Comment by merlip91** [comment]
Problem solved, thanks a lot!
