### ISSUE TITLE
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet

### ISSUE THREAD

**Issue by evilcore** [wdullaer/MaterialDateTimePicker#213]
On emulator Nexus android 4.0 arm cpu:
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
                                                                                              at android.animation.AnimatorSet.sortNodes(AnimatorSet.java:816)
                                                                                              at android.animation.AnimatorSet.start(AnimatorSet.java:454)
                                                                                              at com.wdullaer.materialdatetimepicker.time.RadialPickerLayout.setCurrentItemShowing(RadialPickerLayout.java:682)
                                                                                              at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.setCurrentItemShowing(TimePickerDialog.java:939)
                                                                                              at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.advancePicker(TimePickerDialog.java:765)
                                                                                              at com.wdullaer.materialdatetimepicker.time.RadialPickerLayout.onTouch(RadialPickerLayout.java:857)
                                                                                              at android.view.View.dispatchTouchEvent(View.java:5481)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1953)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1714)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
                                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1892)
                                                                                              at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371)
                                                                                              at android.app.Dialog.dispatchTouchEvent(Dialog.java:725)
                                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1840)
                                                                                              at android.view.View.dispatchPointerEvent(View.java:5662)
                                                                                              at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2863)
                                                                                              at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:4340)
                                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by wdullaer** [comment]
I can't reproduce this, and I can't really see anything wrong at the code positions mentioned in the stacktrace.

You're going to have to give me some more information
