### ISSUE TITLE
  java.lang.NoClassDefFoundError: com.wdullaer.materialdatetimepicker.R$string

### ISSUE THREAD

**Issue by egemendurmus** [wdullaer/MaterialDateTimePicker#234]
hi ; i try this libs works lolipop but in in kitkat not works it gives this error  what is the cause this ; 

 java.lang.NoClassDefFoundError: com.wdullaer.materialdatetimepicker.R$string
                                                                                      at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.<init>(DatePickerDialog.java:137)
                                                                                      at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.newInstance(DatePickerDialog.java:189)
                                                                                      at com.example.egemendurmus.deneme.current_order.ViewPagerAdapter.instantiateItem(ViewPagerAdapter.java:237)
                                                                                      at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:943)
                                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1091)
                                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                                      at android.view.View.measure(View.java:16497)

**Comment by wdullaer** [comment]
Try a build clean

**Comment by egemendurmus** [comment]
not working :/ ; order is fragment is it affect ?

gives error first line 

  DatePickerDialog dpd = DatePickerDialog.newInstance(
                        order.this,
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)

                );

**Comment by egemendurmus** [comment]
I found cause it is crashed with com.facebook.android:facebook-android-sdk:4.15.0 why give this error ?

**Comment by wdullaer** [comment]
This is pretty clearly an issue with your code / build chain, rather than this library.
Java stacktraces and build time errors are notoriously vague.
