### ISSUE TITLE
throw IllegalStateException when picker.show(FragmentManager manager, String tag)

### ISSUE THREAD

**Issue by yezishu** [wdullaer/MaterialDateTimePicker#330]
throw IllegalStateException : Fragment already added when picker.show(FragmentManager manager, String tag) 
rush log 
`java.lang.IllegalStateException: Fragment already added: DatePickerDialog{a4b97bb #0 datePicker}
at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1150)
at android.app.BackStackRecord.run(BackStackRecord.java:773)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:457)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5692)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

it's because double show the picker to FragmentManager
Now ,I fix it 
`    public void showDatePicker() {
        if(dpd!=null
                &&!dpd.isAdded())
            dpd.show(activity.getFragmentManager(), DATE_PICKER);
    }`

**Comment by wdullaer** [comment]
This sounds like a logic bug in your application.
You are recycling the datepickerdialog instance and calling build twice on it somehow.

**Comment by yezishu** [comment]
find this bug by compatibility test ，and repeat in AndroidStudio debug pattern
