### ISSUE TITLE
NPE using DateRangeLimiter

### ISSUE THREAD

**Issue by s3r6** [wdullaer/MaterialDateTimePicker#393]
Created the following class to limit the select to work days only

```java
public class HolidayDateRangeLimiter implements DateRangeLimiter {
  public HolidayDateRangeLimiter() {
  }

  public HolidayDateRangeLimiter(Parcel in) {
  }

  @Override
  public int getMinYear() {
    return 0;
  }

  @Override
  public int getMaxYear() {
    return 0;
  }

  @Override
  public Calendar getStartDate() {
    return null;
  }

  @Override
  public Calendar getEndDate() {
    return null;
  }

  /** Запрещаем выбирать выходные дни. В идеале можно передавать сюда список праздничных дней текущего года. */
  @Override
  public boolean isOutOfRange(int year, int month, int day) {
    Calendar calendar = Calendar.getInstance();
    calendar.set(Calendar.YEAR, year);
    calendar.set(Calendar.MONTH, month);
    calendar.set(Calendar.DAY_OF_MONTH, day);
    int dayOfWeek = calendar.get(Calendar.DAY_OF_WEEK);
    // выходной день
    return dayOfWeek == Calendar.SATURDAY || dayOfWeek == Calendar.SUNDAY;
  }

  @Override
  public Calendar setToNearestDate(Calendar day) {
    return null;
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(Parcel dest, int flags) {
  }

  public static final Creator<HolidayDateRangeLimiter> CREATOR = new Creator<HolidayDateRangeLimiter>() {
    @Override
    public HolidayDateRangeLimiter createFromParcel(Parcel source) {
      return new HolidayDateRangeLimiter(source);
    }

    @Override
    public HolidayDateRangeLimiter[] newArray(int size) {
      return new HolidayDateRangeLimiter[size];
    }
  };
}
```

and set it like this `dpd.setDateRangeLimiter(new HolidayDateRangeLimiter());`

When opening dialog there is NPE

```
java.lang.NullPointerException
at com.wdullaer.materialdatetimepicker.date.MonthAdapter$CalendarDay.<init>(MonthAdapter.java:65)
at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.getSelectedDay(DatePickerDialog.java:984)
at com.wdullaer.materialdatetimepicker.date.MonthAdapter.<init>(MonthAdapter.java:112)
at com.wdullaer.materialdatetimepicker.date.SimpleMonthAdapter.<init>(SimpleMonthAdapter.java:27)
at com.wdullaer.materialdatetimepicker.date.SimpleDayPickerView.createMonthAdapter(SimpleDayPickerView.java:37)
at com.wdullaer.materialdatetimepicker.date.DayPickerView.refreshAdapter(DayPickerView.java:147)
at com.wdullaer.materialdatetimepicker.date.DayPickerView.setController(DayPickerView.java:99)
at com.wdullaer.materialdatetimepicker.date.DayPickerView.<init>(DayPickerView.java:91)
at com.wdullaer.materialdatetimepicker.date.SimpleDayPickerView.<init>(SimpleDayPickerView.java:32)
at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:331)
at android.app.Fragment.performCreateView(Fragment.java:1700)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
at android.app.BackStackRecord.run(BackStackRecord.java:684)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5756)
```

Expected: limitation works. There is no need for me to implement other limitations in the class.

**Comment by wdullaer** [comment]
You should not return `null` from `getStartDate()` and `getEndDate()`.
The implementations in `DefaultDateRangeLimiter` are even annotated `@NonNull`

I should move those annotations to the interface

**Comment by s3r6** [comment]
I think there should be an abstract `DateRangeLimiter` implementation to extend for those who does not need all restrictions.

**Comment by wdullaer** [comment]
I understand what you're saying, but this is already an 'expert' feature.

I might do it if I have some time, but it's not a massive priority right now.

**Comment by wdullaer** [comment]
I've added annotations to the interface in v26.0.1, making it more clear that `getStartDate()` and `getEndDate()` cannot return `null`
