### ISSUE TITLE
Exception on SDK Version < M

### ISSUE THREAD

**Issue by SantiDev** [wdullaer/MaterialDateTimePicker#403]
```
android.view.InflateException: Binary XML file line #0: Error inflating class TextView
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:855)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:751)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
 at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:318)
 at android.app.Fragment.performCreateView(Fragment.java:1700)
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
 at android.app.BackStackRecord.run(BackStackRecord.java:684)
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
 at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
 at android.os.Handler.handleCallback(Handler.java:733)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:146)
 at android.app.ActivityThread.main(ActivityThread.java:5602)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=21; index=1740
 at android.content.res.StringBlock.get(StringBlock.java:65)
 at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:459)
 at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:721)
 at android.content.res.TypedArray.getString(TypedArray.java:125)
 at android.widget.TextView.<init>(TextView.java:1509)
 at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:75)
 at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
 at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
 at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
 at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:855) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:751) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
 at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:318) 
 at android.app.Fragment.performCreateView(Fragment.java:1700) 
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
 at android.app.BackStackRecord.run(BackStackRecord.java:684) 
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453) 
 at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
 at android.os.Handler.handleCallback(Handler.java:733) 
 at android.os.Handler.dispatchMessage(Handler.java:95) 
 at android.os.Looper.loop(Looper.java:146) 
 at android.app.ActivityThread.main(ActivityThread.java:5602) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:515) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
 at dalvik.system.NativeStart.main(Native Method) 

```
----------
Your code 
` mVersion = Build.VERSION.SDK_INT < Build.VERSION_CODES.M ? Version.VERSION_1 : Version.VERSION_2;`

 I fixed it by 
`datePickerDialog.setVersion(DatePickerDialog.Version.VERSION_2);`

**Comment by wdullaer** [comment]
I can't reproduce this on the emulator.

What language is the device on which this happened using?

**Comment by SantiDev** [comment]
Android OS: N
Device: Galaxy S7
Language: English

**Comment by wdullaer** [comment]
You can't encounter this message on a device running android N and then claim that it only occurs on M and below.

Can you reproduce the error with just the sample app?
