### ISSUE TITLE
TimePickerDialog crashes going to background on version 3.3.0

### ISSUE THREAD

**Issue by jrgonzalezg** [wdullaer/MaterialDateTimePicker#404]
Since we updated to Material DateTime Picker 3.3.0 we are seeing these crashes that did not occur on version 3.2.2:
```
Fatal Exception: java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.wdullaer.materialdatetimepicker.time.Timepoint[]
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.writeToParcel(DefaultTimepointLimiter.java:42)
       at android.os.Parcel.writeParcelable(Parcel.java:1357)
       at android.os.Parcel.writeValue(Parcel.java:1262)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.FragmentState.writeToParcel(Fragment.java:139)
       at android.os.Parcel.writeTypedArray(Parcel.java:1191)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
       at android.os.Parcel.writeParcelable(Parcel.java:1357)
       at android.os.Parcel.writeValue(Parcel.java:1262)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2963)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3453)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

To reproduce, simply open a TimePickerDialog and make it go to background by clicking the recents button on your device. It crashes immediately after doing so trying to parcel some state so it seems something changed there since version 3.2.2. Sorry I have no time to look at the code of this issue more deeply right now but I hope the stacktrace helps.

**Comment by JorgeCastilloPrz** [comment]
Feels like a quite important issue to fix. +1!

**Comment by wdullaer** [comment]
I will look at this shortly

**Comment by felipezf** [comment]
+1 here

**Comment by wdullaer** [comment]
I've got this fixed locally.
Will try to make a release somewhere this week
