### ISSUE TITLE
Native Typeface Error.

### ISSUE THREAD

**Issue by HelloSpoon** [wdullaer/MaterialDateTimePicker#41]
Hi, I'm trying to use this library on my smartphone running Android 4.0 but I'm having this error:
```
06-05 15:53:54.036: E/AndroidRuntime(19147): FATAL EXCEPTION: main
06-05 15:53:54.036: E/AndroidRuntime(19147): java.lang.RuntimeException: native typeface cannot be made
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.graphics.Typeface.<init>(Typeface.java:175)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.graphics.Typeface.createFromAsset(Typeface.java:149)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at com.wdullaer.materialdatetimepicker.TypefaceHelper.get(TypefaceHelper.java:31)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:262)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.Fragment.performCreateView(Fragment.java:1699)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.BackStackRecord.run(BackStackRecord.java:694)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.os.Handler.handleCallback(Handler.java:800)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.os.Looper.loop(Looper.java:194)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at android.app.ActivityThread.main(ActivityThread.java:5391)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at java.lang.reflect.Method.invoke(Method.java:525)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
06-05 15:53:54.036: E/AndroidRuntime(19147): 	at dalvik.system.NativeStart.main(Native Method)
```
It's related to the Typeface loading as I can read.
Is somebody having this same issue?
How did you solve it?

**Comment by HelloSpoon** [comment]
Ok, I just solved it by modifying the TypefaceHelper.java file.
Changed the SimpleArrayMap structure by a Hastable structure.
Here is the new TypefaceHelper.java:

```
public class TypefaceHelper{
	private static final Hashtable<String, Typeface> cache = new Hashtable<String, Typeface>();
	
	public static Typeface get(Context c, String assetPath){
		synchronized (cache){
			if(!cache.containsKey(assetPath)){
				try{
					Typeface t = Typeface.createFromAsset(c.getAssets(), String.format("fonts/%.ttf", assetPath));
					cache.put(assetPath, t);
				} catch(Exception e){
					return null;
				}
			}
			return cache.get(assetPath);
		}
	}

}
```

**Comment by wdullaer** [comment]
SimpleArrayMap is a more lightweight drop in replacement for HashMap.
It's part of the v4 support library, so it shouldn't be causing any issues on Android 4.0

Were you using the version from Maven central or did you build it yourself?
In case you've build it yourself, a clean build might help to resolve all the dependencies properly.

Also the exception you're showing is related to creating the typeface, rather than an operation on the SimpleArrayMap.
Rather than changing the container, I think the rebuild that it triggered fixed your issue.

Can you roll back your change and verify this?

**Comment by HelloSpoon** [comment]
Hi, yes I can take a look to it in a couple days. 
I'll post the result of changing Hashtable to SimpleArrayMap again :-).

**Comment by HelloSpoon** [comment]
Hi, 
I changed the structure from Hashtable to SimpleArrayMap and it didn't crashed but when I changed my modified code for yours it crashed again with the same error. So, I just re-wrote the one you code and it worked as you said (kind of weird if you ask me).

Thanks!

**Comment by wdullaer** [comment]
Modern IDEs aggressively cache build results.
In any case, I'm happy it's resolved :-)
