### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException java.lang.Object[] cannot be cast to com.wdullaer.materialdatetimepicker.time.c[]

### ISSUE THREAD

**Issue by ankurvs** [wdullaer/MaterialDateTimePicker#410]
I am getting this issue after updating supporting library 26.
Here the logs:

**Fatal Exception: java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.wdullaer.materialdatetimepicker.time.c[]
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.writeToParcel(DefaultTimepointLimiter.java:42)
       at android.os.Parcel.writeParcelable(Parcel.java:1292)
       at android.os.Parcel.writeValue(Parcel.java:1211)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:643)
       at android.app.FragmentState.writeToParcel(Fragment.java:133)
       at android.os.Parcel.writeTypedArray(Parcel.java:1140)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:373)
       at android.os.Parcel.writeParcelable(Parcel.java:1292)
       at android.os.Parcel.writeValue(Parcel.java:1211)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:643)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2556)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3278)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)**

**Comment by jbollacke** [comment]
Received the same crashlog today. Can reproduce it on activity restart.

I don't think this is related to the support library version though as the app in question is still on v24.2.1.

**Comment by jbollacke** [comment]
This issue is fixed in v3.3.1. Please upgrade.
