### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: minYear > maxYear

### ISSUE THREAD

**Issue by antoxa2584x** [wdullaer/MaterialDateTimePicker#413]
Galaxy S3 Neo
4.4.2

```
Fatal Exception: java.lang.IllegalArgumentException: minYear > maxYear
       at com.wdullaer.materialdatetimepicker.date.YearPickerView$YearAdapter.<init>(YearPickerView.java:100)
       at com.wdullaer.materialdatetimepicker.date.YearPickerView.init(YearPickerView.java:67)
       at com.wdullaer.materialdatetimepicker.date.YearPickerView.<init>(YearPickerView.java:59)
       at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:334)
       at android.app.Fragment.performCreateView(Fragment.java:1700)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.BackStackRecord.run(BackStackRecord.java:684)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5476)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by wdullaer** [comment]
As it says in the exception: your minimum year is above your maximum year, so there is no valid selection possible.
