### ISSUE TITLE
Conflict with support.v4.Fragment ?

### ISSUE THREAD

**Issue by maxbaldrighi** [wdullaer/MaterialDateTimePicker#421]
What I am about to write might seem very weird, but I really think it's directly related to this library.

First of all, issue experienced on:
 - API 24 (physical device)
 - API 19 (physical device)

It's been since yesterday that I'm dealing with an issue on one of my fragments. My project uses the support library and I know that this library doesn't.

I have several activities A, B, etc, each containing two or more fragments (1), (2), etc., to which and from which I move with simple *replace()* calls.
Now, before yesterday everything worked fine, but now in **only one** of these activities I face an IllegalStateException crash, dealing with a *super.onBackPressed()* call in order to move back from fragent (2) to (1):
`java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first. android fragments
at android.view.ViewGroup.addViewInner(ViewGroup.java:3733)
                                                                                    at android.view.ViewGroup.addView(ViewGroup.java:3579)
                                                                                    at android.view.ViewGroup.addView(ViewGroup.java:3524)
                                                                                    at android.view.ViewGroup.addView(ViewGroup.java:3500)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                    at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:855)
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2587)
                                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                                    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:851)
                                                                                    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:794)
                                                                                    at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:181)
                                                                                    at it.easymoove.activities_tracking.TrackingActivity.onBackPressed(TrackingActivity.java:77)
                                                                                    at it.easymoove.activities_tracking.TrackingActivity.removeCurrentFragment(TrackingActivity.java:128)
                                                                                    at it.easymoove.activities_tracking.RequestTrackingFragmentNoMap.onBackAction(RequestTrackingFragmentNoMap.java:361)
                                                                                    at it.easymoove.activities_tracking.RequestTrackingFragmentNoMap.onBackPressed(RequestTrackingFragmentNoMap.java:1148)
                                                                                    at it.easymoove.activities_tracking.TrackingActivity.onBackPressed(TrackingActivity.java:73)
                                                                                    at it.easymoove.activities_tracking.TrackingActivity.removeCurrentFragment(TrackingActivity.java:128)
                                                                                    at it.easymoove.activities_tracking.TrackingReachPickupPointFragment.onBackPressed(TrackingReachPickupPointFragment.java:305)
                                                                                    at it.easymoove.activities_tracking.TrackingReachPickupPointFragment.onClick(TrackingReachPickupPointFragment.java:176)
                                                                                    at android.view.View.performClick(View.java:4480)
                                                                                    at android.view.View$PerformClick.run(View.java:18796)
                                                                                    at android.os.Handler.handleCallback(Handler.java:808)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5398)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
                                                                                    at dalvik.system.NativeStart.main(Native Method)`

I checked out every single commit in a while, and noticed that this issue appears from the commit in which I just add the "compile ..." line of this library in my app/build.gradle file.
If I remove every single reference to this project and clean mine, then everything starts working again.

I know it's a long shot, but do you have any idea on what might affect a fragment popping from the backstack?

**Comment by wdullaer** [comment]
This is indeed weird.
The library does not use support fragments, but it does use the support library for some other features.

My current guess is that you are using a different version of the support library in your app. You could try to exclude compiling the transitive support library dependency (this is explained in the Readme)

Do any of these fragments create pickers?

**Comment by maxbaldrighi** [comment]
Thank you for your reply!

No, the only pickers are created in my main Activity that has no fragments in it.

**Comment by maxbaldrighi** [comment]
I definitely should have read your explanations more carefully and try to exclude support dependencies in the first place... IT WORKED!
Now that fragment behaves exactly like the others. It still bothers me, though, why it was just **that** fragment, while the same pattern of *replacing-and-back* used for many others fragments kept working fine...
If I ever have some news about this, I will report here!
Thanks again for your help!

**Comment by wdullaer** [comment]
If you ever find out, please let me know. I'm happy things started working for you 😎
