### ISSUE TITLE
NullPointerException for use onDayOfMonthSelected method

### ISSUE THREAD

**Issue by a1018875550** [wdullaer/MaterialDateTimePicker#422]
I'm add this code ```  dpd.onDayOfMonthSelected(2017,11,20);``` in demo,then
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                                              at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.updateDisplay(DatePickerDialog.java:531)
                                                                                              at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onDayOfMonthSelected(DatePickerDialog.java:979)
                                                                                              at com.wdullaer.datetimepickerexample.DatePickerFragment$1.onClick(DatePickerFragment.java:71)
                                                                                              at android.view.View.performClick(View.java:6256)
                                                                                              at android.view.View$PerformClick.run(View.java:24701)
                                                                                              at android.os.Handler.handleCallback(Handler.java:789)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by wdullaer** [comment]
That's an internal callback. I should reduce e its visibility.
It assumes the picker is visible which in your case it isn't, hence the npe.
You shouldn't be using this method.

**Comment by a1018875550** [comment]
so, how do I set the default choose date or time? thanks!

**Comment by wdullaer** [comment]
As parameters of the newInstance method. Look at the example in the Readme.

**Comment by a1018875550** [comment]
thanks!
