### ISSUE TITLE
Date picker is crash some time in 3.3.1 version.

### ISSUE THREAD

**Issue by ankurvs** [wdullaer/MaterialDateTimePicker#424]
Caused by java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to com.wdullaer.materialdatetimepicker.time.c[]
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.(DefaultTimepointLimiter.java)
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter$1.createFromParcel(DefaultTimepointLimiter.java:54)
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter$1.createFromParcel(DefaultTimepointLimiter.java:52)
       at android.os.Parcel.readParcelable(Parcel.java:2262)
       at android.os.Parcel.readValue(Parcel.java:2162)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2495)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:822)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:836)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1054)
       at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1900)
       at android.app.Activity.onCreate(Activity.java:959)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:278)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at com.mychoize.cars.common.BaseActivity.onCreate(BaseActivity.java:54)
       at com.mychoize.cars.ui.home.ModifySearchScreen.onCreate(ModifySearchScreen.java:64)
       at android.app.Activity.performCreate(Activity.java:6177)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
       at android.app.ActivityThread.access$900(ActivityThread.java:188)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

I m using 3.3.1 Version.

**Comment by wdullaer** [comment]
Please try to reproduce this on the latest version
