### ISSUE TITLE
There are some errors!!

### ISSUE THREAD

**Issue by DennyCai** [wdullaer/MaterialDateTimePicker#48]
This is my style resources
<resources>

    <style name="Base.Theme.HMKCodeApp" parent="Theme.AppCompat.Light.NoActionBar">

        <item name="colorPrimary">@color/my_primary</item>

        
        <item name="colorPrimaryDark">@color/my_primary_dark</item>

        
        <item name="colorAccent">@color/my_accent</item>

        
        <item name="android:textColorPrimary">@color/my_primary_text</item>

        
        <item name="android:textColorSecondary">@color/my_secondary_text</item>

        
        <item name="windowActionModeOverlay">true</item>

        

        
        <item name="textAppearanceLargePopupMenu">@style/MyTextAppearance.Widget.PopupMenu</item>
    </style>

    
    <style name="MyTextAppearance.Widget.PopupMenu" parent="TextAppearance.AppCompat.Light.Widget.PopupMenu.Large">
        <item name="android:textColor">@color/primary_material_dark</item>
    </style>

    
    <style name="AppBaseTheme" parent="Base.Theme.HMKCodeApp">
        
    </style>
    

    
    <style name="AppTheme" parent="AppBaseTheme">
        
    </style>

    <style name="Widget.CardContent" parent="android:Widget">
        <item name="android:paddingLeft">16dp</item>
        <item name="android:paddingRight">16dp</item>
        <item name="android:paddingTop">24dp</item>
        <item name="android:paddingBottom">24dp</item>
        <item name="android:orientation">vertical</item>
    </style>

</resources>
when I declaration [android:theme="@style/AppTheme"] in my AndroidManifest,and start up my App.
The Application throw some errors 

06-24 10:15:33.792    2128-2128/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.denny.android.idea_note, PID: 2128
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.denny.android.idea_note/com.denny.android.idea_note.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5050)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
            at com.denny.android.idea_note.MainActivity.onCreate(MainActivity.java:53)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5050)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wdullaer** [comment]
You should read your stacktrace:
```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```
This is not in the slightest related to this library, so I'm closing the issue.

**Comment by chongivan** [comment]
I think @DennyCai's talking about this issue
https://github.com/flavienlaurent/datetimepicker/issues/82

**Comment by wdullaer** [comment]
There really is no issue here, from the perspective of this library.
This library does not depend on AppCompat, but is fully compatible with it (I know because I'm using it that way myself).

**Comment by DennyCai** [comment]
@chongivan Thank you so much!

**Comment by sanif** [comment]
Late but may help someone. I had also faced the same issue. It is because the library uses the names "AppTheme"  and "AppBaseTheme" as its internal theme names. So there will be conflict between those names in your project and in library. The solution is to rename your theme to  something like "AppBaseTheme2". Hope it will help.
