### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by leventepal** [wdullaer/MaterialDateTimePicker#493]
Version 3.5.2:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference
       at java.util.TreeMap.compare(TreeMap.java:1321)
       at java.util.TreeMap.getFloorEntry(TreeMap.java:430)
       at java.util.TreeMap.floorKey(TreeMap.java:760)
       at java.util.TreeSet.floor(TreeSet.java:425)
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.roundToNearest(DefaultTimepointLimiter.java:204)
       at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.roundToNearest(TimePickerDialog.java:1176)
       at com.wdullaer.materialdatetimepicker.time.RadialPickerLayout.roundToValidTime(RadialPickerLayout.java:452)
       at com.wdullaer.materialdatetimepicker.time.RadialPickerLayout.access$000(RadialPickerLayout.java:51)
       at com.wdullaer.materialdatetimepicker.time.RadialPickerLayout$5.run(RadialPickerLayout.java:776)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by wdullaer** [comment]
The stacktrace as such doesn't help much.
Can you paste the code where you are configuring the picker?

**Comment by leventepal** [comment]
This is a crash reported by crashlytics, it has crashed for one of the users having:

SM-G955U, Android O.

This is the only stacktrace that the website it's offering to me.

**Comment by wdullaer** [comment]
I don't need more information on the device.
There is nothing particularly wrong with the code pointed at by the stacktrace, and there's even a reasonable test suite backing up that claim.

As I mentioned earlier: I'll need to see the code where you are configuring the picker and preferably also some information on how you are constructing the inputs for `setSelectableTimes` and `setDisabledTimes` to be able to help you debug this.

**Comment by wdullaer** [comment]
This should not be possible: all these calls have NonNull annotations and setTimeInterval cannot produce null objects. So the compiler should enforce that neither part of the comparison can be null.

How many reports do you have like this?

**Comment by leventepal** [comment]
Sorry for late response, I've had 2 reports but it's look like it's working. I don't know what caused the problem.

**Comment by wdullaer** [comment]
Please reopen this, or create a new issue if the problem reappears.
