### ISSUE TITLE
Crash in DayPickerView

### ISSUE THREAD

**Issue by mstberto** [wdullaer/MaterialDateTimePicker#499]
When performing unit tests with Robolectric and version 3.6.1, I found a crash in the DayPickerView in the following lines of code.

https://github.com/wdullaer/MaterialDateTimePicker/blob/2d21725bf19b7e66d3e40f78d80c3d2a7fc10c3e/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DayPickerView.java#L249

It looks like this is because in the following constructor:

https://github.com/wdullaer/MaterialDateTimePicker/blob/2d21725bf19b7e66d3e40f78d80c3d2a7fc10c3e/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DayPickerView.java#L82

setController is called prior to init. This leaves open an opportunity for a crash when setController triggers onDateChanged() which manipulates the view prior to it being fully initialized via init(). It looks like the code itself hasn't changed too much since it was last working on 3.4.1 so I'm not sure what the actual change that caused this was.

Stacktrace:

> java.lang.NullPointerException
	at com.wdullaer.materialdatetimepicker.date.DayPickerView$2.run(DayPickerView.java:249)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:319)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:156)
	at org.robolectric.util.Scheduler.post(Scheduler.java:135)
	at org.robolectric.shadows.ShadowView.post(ShadowView.java:402)
	at android.view.View.post(View.java)
	at com.wdullaer.materialdatetimepicker.date.DayPickerView.postSetSelection(DayPickerView.java:245)
	at com.wdullaer.materialdatetimepicker.date.DayPickerView.goTo(DayPickerView.java:235)
	at com.wdullaer.materialdatetimepicker.date.DayPickerView.onDateChanged(DayPickerView.java:301)
	at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.updatePickers(DatePickerDialog.java:1077)
	at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onDayOfMonthSelected(DatePickerDialog.java:1068)

**Comment by wdullaer** [comment]
I'll take a look at this, hopefully the race condition can be removed.

Would you be open to incorporating the unit tests in this repository?
I haven't been able to find the time to add UI based tests myself.

**Comment by wdullaer** [comment]
I think I managed to resolve this issue.

I would still be very interested in adding some of your test suite to this library to help me confirm that it's fixed and prevent future regressions :-)

**Comment by thalles89** [comment]
Hi brother, i've couldn't use the .setDisabledDays and .setDisabledTime, so, how can i do to use this?
