### ISSUE TITLE
Crash with mindate

### ISSUE THREAD

**Issue by Bobkovn** [wdullaer/MaterialDateTimePicker#522]
If we set a minimum date and try a quick moving datepiker, in some cases an arrow may appear, which moves to the previous month from the minimum date.
![screenshot_2018-09-03-13-23-46](https://user-images.githubusercontent.com/10584671/45099372-c3b81300-b12f-11e8-8a7f-a5f85622a6a6.png)
When you click on this arrow, the application crashes with such an error
`java.lang.IllegalArgumentException: Invalid target position
        at android.support.v7.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:11377)
        at android.support.v7.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:8090)
        at android.support.v7.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:453)
        at android.support.v7.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1700)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onClick(DayPickerGroup.java:178)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24774)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by wdullaer** [comment]
I think this issue is similar to #499 
I thought I had released this one already, but that appears not to be the case.
I'll try to get that sorted soon
