### ISSUE TITLE
InflationException with DatepickerDialog

### ISSUE THREAD

**Issue by moda20** [wdullaer/MaterialDateTimePicker#524]
hi !

I am calling this repo in a Cordova plugin and encountered this problem. 

here is the calling code :

```java
 Calendar now = Calendar.getInstance();
            DatePickerDialog dpd =  DatePickerDialog.newInstance(
                     new DatePickerDialog.OnDateSetListener(){
                        @Override
                        public void onDateSet(DatePickerDialog view, int year, int month, int dayOfMonth) {
                            Log.d("Orignal", "Got clicked");
                        }
                    },
                    now.get(Calendar.YEAR),
                    now.get(Calendar.MONTH),
                    now.get(Calendar.DAY_OF_MONTH)
            );
            /*dpd.setThemeDark(true);*/
            /*dpd.setAccentColor(Color.parseColor("#9C27B0"));*/
            dpd.show(cordova.getActivity().getFragmentManager(),"Datepickerdialog");
```

```
android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class android.widget.ImageButton
    Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class android.widget.ImageButton
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.init(DayPickerGroup.java:50)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.<init>(DayPickerGroup.java:32)
        at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:370)
        at android.app.Fragment.performCreateView(Fragment.java:2352)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
        at android.app.BackStackRecord.run(BackStackRecord.java:815)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6275)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f030100 a=-1}
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363)
        at android.view.View.<init>(View.java:4230)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.view.View.<init>(<Xposed>)
        at android.widget.ImageView.<init>(ImageView.java:150)
        at android.widget.ImageButton.<init>(ImageButton.java:84)
        at android.widget.ImageButton.<init>(ImageButton.java:80)
```

any help ?

**Comment by chdh** [comment]
I have exactly the same error in a normal Java Android app (without Cordova):

```
android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class android.widget.ImageButton
Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class android.widget.ImageButton
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    at android.view.LayoutInflater.createView(LayoutInflater.java:647)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.init(DayPickerGroup.java:50)
    at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.<init>(DayPickerGroup.java:32)
    at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:370)
    at android.app.Fragment.performCreateView(Fragment.java:2508)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
    at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
    at android.app.BackStackRecord.executeOps(BackStackRecord.java:807)
    at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2386)
    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2181)
    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2136)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f030136 a=-1}
    at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
    at android.view.View.<init>(View.java:4768)
    at android.widget.ImageView.<init>(ImageView.java:176)
    at android.widget.ImageButton.<init>(ImageButton.java:86)
    at android.widget.ImageButton.<init>(ImageButton.java:82)
    at android.widget.ImageButton.<init>(ImageButton.java:78)
    at java.lang.reflect.Constructor.newInstance0(Native Method) 
    at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
    at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.init(DayPickerGroup.java:50) 
    at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.<init>(DayPickerGroup.java:32) 
    at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:370) 
    at android.app.Fragment.performCreateView(Fragment.java:2508) 
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279) 
    at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557) 
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618) 
    at android.app.BackStackRecord.executeOps(BackStackRecord.java:807) 
    at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2386) 
    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2181) 
    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2136) 
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043) 
    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719) 
    at android.os.Handler.handleCallback(Handler.java:790) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6494) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

```

**Comment by chdh** [comment]
The error occurs because the `ImageButton`s in [mdtp_daypicker_group.xml](https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/res/layout/mdtp_daypicker_group.xml) have the following attribute reference:

```
android:background="?attr/selectableItemBackgroundBorderless"`
```

This works when the style theme of the activity is `Theme.AppCompat.Light.NoActionBar`, but not with e.g. `@android:style/Theme.Material.Light`.

As a workaround, you can add the follwing definition to your `AppTheme`:

```
<item name="selectableItemBackgroundBorderless">?android:attr/selectableItemBackgroundBorderless</item>
```

**Comment by wdullaer** [comment]
Thanks for investigating this a bit more.
There was another issue recently which caused confusion for a user because I was using theme attributes.
I should try to phase these out.

**Comment by chdh** [comment]
@wdullaer Thanks for your work.

The workaround did not work with Android 4.1. I had to set the `selectableItemBackgroundBorderless` item to a color.

**Comment by moda20** [comment]
I did find a way to make it work, by changing 
`android:background="?attr/selectableItemBackgroundBorderless"
`
to 

`android:background="?android:attr/selectableItemBackgroundBorderless"
`

on mdtp_daypicker_group in the two `ImageButton`

**Comment by wdullaer** [comment]
This is fixed in the latest version, you should use that one.

Your solution is only valid on API 21+, the attribute `?android:attr/selectableItemBackgroundBorderless` does not exist on older versions.
