### ISSUE TITLE
App crashes when dates are disabled and user clicks on visible dates on sample app

### ISSUE THREAD

**Issue by him2016** [wdullaer/MaterialDateTimePicker#561]
**App crashes with following stacktrace:**
```
java.lang.NullPointerException: Attempt to read from field 'int com.wdullaer.materialdatetimepicker.date.MonthView.mMonth' on a null object reference
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.accessibilityAnnouncePageChanged(DayPickerView.java:358)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onPageChanged(DayPickerGroup.java:165)
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.lambda$postSetSelection$1(DayPickerView.java:243)
        at com.wdullaer.materialdatetimepicker.date.-$$Lambda$DayPickerView$lwj6z_px0zTXu4FzUTw4TbYiZpk.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Please help.

**Comment by wdullaer** [comment]
Are you using the latest version?

**Comment by him2016** [comment]
I have added this in the gradle file:

implementation 'com.wdullaer:materialdatetimepicker:4.1.1'

I guess it is the latest version..

**Comment by him2016** [comment]
@wdullaer Did you get time to have a look?

**Comment by steve-the-edwards** [comment]
+1 this is happening in my application as well with showYearPickerFirst(true) on latest version 4.1.1.

**Comment by steve-the-edwards** [comment]
To me - it looks the same as https://github.com/wdullaer/MaterialDateTimePicker/issues/554.  Can you add the null check to prevent this while we continue to track down the root?

**Comment by wdullaer** [comment]
There's already a PR for this (see #564 )
I need some time to do actually merge and release everything.

**Comment by him2016** [comment]
Issue resolved now.. thanks.. keep up the good work..
