### ISSUE TITLE
Which version works of this library works with API 15?

### ISSUE THREAD

**Issue by wdullaer** [wdullaer/MaterialDateTimePicker#572]
Which version works of this library works with API 15?

Technically this is my issue:

03-11 17:31:03.604 31974-31974/org.development.aihd.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.development.aihd.app, PID: 31974
    java.lang.IllegalStateException: Could not find a method dob(View) in the activity class android.support.v7.widget.TintContextWrapper for onClick handler on view class customfonts.EditText_Roboto_Regular with id 'birthdate'
        at android.view.View$1.onClick(View.java:3847)
        at android.view.View.performClick(View.java:4508)
        at android.view.View$PerformClick.run(View.java:18675)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5590)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoSuchMethodException: dob [class android.view.View]
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)

_Originally posted by @cromwel in https://github.com/wdullaer/MaterialDateTimePicker/issues/420#issuecomment-471563955_

**Comment by wdullaer** [comment]
@cromwel please create a new issue for new questions

Support for API 14 and 15 was dropped in v4.

Any version before that should work on the API levels.

Please refer to the release section for more information.
