### ISSUE TITLE
NullPointerException on getMonthHeight

### ISSUE THREAD

**Issue by Cylix** [wdullaer/MaterialDateTimePicker#591]
Hi,

I got the following crash:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.wdullaer.materialdatetimepicker.date.SimpleMonthView.getMonthHeight()' on a null object reference
       at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onLayout(DayPickerGroup.java:142)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
       at android.view.View.layout(View.java:22399)
       at android.view.ViewGroup.layout(ViewGroup.java:6572)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2804)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

I'm using version `4.1.2` of your library.

It only got triggered for one of our users, but he triggered it 16 times, so I guess there was something wrong for that particular phone/OS.

The user was using a Samsung Galaxy Note 9, running Android 9.

Thanks for the great work btw!

**Comment by wdullaer** [comment]
Is there any special logic around limiting selectable dates in your app?

Maybe for some reason no dates are valid, causing the app to measure a View that doesn't exist.

**Comment by Cylix** [comment]
You're right, after investigation, there were some cases where my `setMaxDate` was before `setMinDate`, resulting in the crash.

Thanks for the hint!
