### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Minimum time must be smaller than the maximum time com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.setMinTime

### ISSUE THREAD

**Issue by Sunaina015** [wdullaer/MaterialDateTimePicker#597]
Fatal Exception: java.lang.IllegalArgumentException: Minimum time must be smaller than the maximum time
       at com.wdullaer.materialdatetimepicker.time.DefaultTimepointLimiter.setMinTime(DefaultTimepointLimiter.java:65)
       at com.wdullaer.materialdatetimepicker.time.TimePickerDialog.setMinTime(TimePickerDialog.java:360)
       at w3bminds.engVarta.app.Helper.TimePickerNew.show(TimePickerNew.java:76)
       at w3bminds.engVarta.app.Activities.ChatTimeActivity$22.onClick(ChatTimeActivity.java:975)
       at android.view.View.performClick(View.java:5619)
       at android.view.View$PerformClick.run(View.java:22298)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6375)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by wdullaer** [comment]
This is intended behaviour. The maximum time is smaller than the minimum time. This means no timepoints are acceptable.
You're trying to put the picker into an illegal state, so it's giving you this exception.
