### ISSUE TITLE
NullPointer if app switcher is opened

### ISSUE THREAD

**Issue by rala72** [wdullaer/MaterialDateTimePicker#609]
I implemented a simple datepicker with some selectable dates.
If the picker is open and I open the app switcher on my Samsung S5 mini running 6.0.1 the app crashes with the following log:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onSaveInstanceState(DatePickerDialog.java:299)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2626)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:134)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
        at android.app.Activity.performSaveInstanceState(Activity.java:1487)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1318)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5489)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4777)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4851)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1850)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7331)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Is there a way to prevent the crash?

**Comment by wdullaer** [comment]
That's a bug. I think I know what's going wrong.
