### ISSUE TITLE
Crash if robotomedium is not available

### ISSUE THREAD

**Issue by ubuntudroid** [wdullaer/MaterialDateTimePicker#621]
I just saw this crash in Crashlytics. Happened to just one user so far, guess they are on some kind of custom ROM, Crashlytics says it is Android 7. Phone is a Tecno WX3 which seems to be a quite low-spec device.

```
Fatal Exception: android.content.res.Resources$NotFoundException: Font resource ID #0x7f090000 could not be retrieved.
       at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:365)
       at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:230)
       at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:423)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

Seems the robotomedium font isn't available. Would it make sense to maybe package it with the library?

**Comment by wdullaer** [comment]
The library does package the font for API versions that do not have it yet.

For API levels that do support roboto medium it points to the framework supplied resource.

If a user removes framework supplied resources, there's not much I can do. The API level is an interface contract, if your device doesn't support all of it, it's not compliant.

**Comment by ubuntudroid** [comment]
Yeah, figured that. Just wanted to quickly double check that the device is really the problem. Will close the issue as indeed there isn't much you can do. Thanks for the quick reply! 🙏
