### ISSUE TITLE
BootstrapMethodError: Exception from call site #3 bootstrap method

### ISSUE THREAD

**Issue by ahamdy96** [wdullaer/MaterialDateTimePicker#624]
I'm facing this exception when calling show(FragmentManager manager, String tag). I'm using the latest version of the library (4.3.2) and java 8 support is enabled in android studio 

```
java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.setUpRecyclerView(DayPickerView.java:119)
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.init(DayPickerView.java:106)
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.<init>(DayPickerView.java:81)
        at com.wdullaer.materialdatetimepicker.date.SimpleDayPickerView.<init>(SimpleDayPickerView.java:32)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.init(DayPickerGroup.java:46)
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.<init>(DayPickerGroup.java:32)
        at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:381)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6693)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.setUpRecyclerView(DayPickerView.java:119) 
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.init(DayPickerView.java:106) 
        at com.wdullaer.materialdatetimepicker.date.DayPickerView.<init>(DayPickerView.java:81) 
        at com.wdullaer.materialdatetimepicker.date.SimpleDayPickerView.<init>(SimpleDayPickerView.java:32) 
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.init(DayPickerGroup.java:46) 
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.<init>(DayPickerGroup.java:32) 
        at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:381) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6693) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
```

**Comment by wdullaer** [comment]
I doubt this is an issue with the code in this library.

The line of the stacktrace is just a constructor of a new object. The constructor takes a lambda and lambda's rely on the InvokeDynamic opcode of the jvm.
Judging by https://docs.oracle.com/javase/7/docs/api/java/lang/BootstrapMethodError.html this exception means the InvokeDynamic call failed.

So either you're running this on a very old runtime / device / custom rom or you haven't correctly enabled java 8 support for backwards compatibility in your project.

**Comment by ahamdy96** [comment]
For Java 8 support, I've already added

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

I thought this was enough to enable java 8 features. 
Anyway, the error disappeared after using retrolambda plugin so I assume the problem is that Java 8 features wasn't enabled correctly

And yes I'm using custom rom, didn't know it may be a cause to such a problem

**Comment by wdullaer** [comment]
Since retrolambda fixes it, it looks like a problem in your build toolchain.
I suggest you read this page in more detail: https://developer.android.com/studio/write/java8-support
