### ISSUE TITLE
DayPickerGroup.java line 58 com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onLayout

### ISSUE THREAD

**Issue by jrodiz** [wdullaer/MaterialDateTimePicker#631]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.wdullaer.materialdatetimepicker.date.SimpleMonthView.getMonthHeight()' on a null object reference
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onLayout(DayPickerGroup.java:142)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2827)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by UnateD** [comment]
Same issue

**Comment by UnateD** [comment]
@jrodiz found a solution
https://github.com/wdullaer/MaterialDateTimePicker/issues/591
