### ISSUE TITLE
Sometimes getMonthHeight() throwing NullPointerException in Fragment

### ISSUE THREAD

**Issue by hanseptiawan** [wdullaer/MaterialDateTimePicker#694]
Hi, I'm using your brilliant library for almost 8 months, and suddenly when i migrate my activity to fragment i found issue that i didn't know how to solve it or what it could be happen in fragment since fragment manager i tried **activity.getSupportFragmentManager()** or **getChildFragmentManager()**, both are still have _NullPointerException_ issue for **getMonthHeight()**. Maybe I'm missed something here, any suggestion ?

here is error log from my debug build
`java.lang.NullPointerException: Attempt to invoke virtual method 'int com.wdullaer.materialdatetimepicker.date.SimpleMonthView.getMonthHeight()' on a null object reference
        at com.wdullaer.materialdatetimepicker.date.DayPickerGroup.onLayout(DayPickerGroup.java:142)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2541)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2257)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)`

thanks

**Comment by hanseptiawan** [comment]
[#591 ](https://github.com/wdullaer/MaterialDateTimePicker/issues/591)

I've got hint from this closed issue, i tried and getMonthHeight() NPE not show up again. I hope it's do the same way for the rest of user's devices. I'll close this issue as soon as there are no crash report about NPE issue

**Comment by hanseptiawan** [comment]
After doing several test from [#591 ](https://github.com/wdullaer/MaterialDateTimePicker/issues/591) reference, I still got NPE issue

I solved with my own solution and NPE issue never happen again tested on several devices that have NPE issue before.
The issue was your max date is lower than min date, please check your year value (if you set max date next year), or others.
This is from the DatePicker framework it self that generated recyclerview date based on your min and max date with condition min is a must lower than max date. Hope it could help someone that still have getMonthHeight() NPE issue.
