### ISSUE TITLE
 App crashes when showing a datePickerdialog on Android 4.1

### ISSUE THREAD

**Issue by Ghostish** [wdullaer/MaterialDateTimePicker#82]
Everything works fine in Lollipop , but the datePickerdialog may cause the APP to be force closed on Android 4.1

**Comment by Ghostish** [comment]
Sorry . I didn't  notice that I were using a old version.

**Comment by Ghostish** [comment]
Here is the log 
AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:316)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
            at android.app.BackStackRecord.run(BackStackRecord.java:635)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5012)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wdullaer** [comment]
Were you by any chance testing this on a device with a resolution like the Nexus S or Nexus One?

**Comment by Ghostish** [comment]
@wdullaer I then tested it on a Genymotion virtual device whose version is 4.1.1 .  No crash happened.
Seems that it is not a problem about OS version.

**Comment by wdullaer** [comment]
I already fixed the issue, I just need to release it.
It has to do with your screen resolution.

**Comment by Ghostish** [comment]
@wdullaer Waiting for the fix haha
